//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteComponentAttribute
    {
        public int QuoteComponentAttributeID { get; set; }
        public int QuoteComponentID { get; set; }
        public string QuoteComponentAttributeCategory { get; set; }
        public string QuoteComponentAttributeType { get; set; }
        public string QuoteComponentAttribute1 { get; set; }
    }
}
